spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      username:
      password:
      uri: mongodb://localhost:27017/chat

    redis:
      host: localhost
      port: 6379
      username:
      password:
