spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      username:
      password:
      uri: ENC(7YAJhJsXKqT+/hTD7P224Tlp842wJnp0flpTDqbyrQrLUg//DtSRZQ==)

    redis:
      host: ENC(yRPbfmLXHWkUeF+8FCzhVQ/TxmGsj7Wm)
      port: ENC(AmGJ5jY3T+1qsG97auYUeA==)
      username:
      password:

  datasource:
    url: ENC(FjETXzrkir2PudjZtVDNVkT+jcU31WG5LDxPDHxfgw28OlMx7Nd/TKw3/A+k867a)
    username: ENC(+3YXkWFLPqCG6jXAtSAmrA==)
    password: ENC(5ZfpUHvNEFFzkJgyjLhjEETADLVKWsIF)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
