spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      username:
      password:
      uri: ENC(J9tApr8Zue8WaqQMVBcix+pFlx/Q9bfswPbcgjRePS8PRSnSiGL72uByOBzh+f8D)

    redis:
      host: ENC(rTZ/dVdh4pZtQIMW3Jh7la6JQsfKyoDo)
      port: ENC(AmGJ5jY3T+1qsG97auYUeA==)
      username:
      password:
