openapi: 3.0.0
info:
  title: 수업 방 API
  version: 1.0.0
  description: 수업 방 API

servers:
  - url: http://localhost:8080
    description: Local server

paths:

  /lessons/{lessonId}/class-room:COMPLETE:
    post:
      summary: 수업 완료
      security:
        - BearerAuth: [ ]
      description: 특정 ID를 가진 수업을 완료 상태로 변경합니다.
      operationId: completeClassRoom
      tags:
        - ClassRoom
      parameters:
        - name: lessonId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 영상 수업 ID
      responses:
        '200':
          description: 성공적으로 수업이 완료되었습니다.
        '400':
          description: 잘못된 요청입니다.
        '404':
          description: 해당 ID의 수업을 찾을 수 없습니다.
        '500':
          description: 서버 오류

  /lessons/{lessonId}/class-room:ENTER:
    post:
      summary: 수업 입장
      security:
        - BearerAuth: [ ]
      description: 수업을 입장.
      operationId: enterClassRoom
      tags:
        - ClassRoom
      parameters:
        - name: lessonId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: 영상 수업 ID
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassRoomEnterResponse'
          description: 성공적으로 수업이 완료되었습니다.
        '400':
          description: 잘못된 요청입니다.
        '401':
          description:
            권한이 없습니다.
        '404':
          description: 해당 ID의 수업을 찾을 수 없습니다.
        '500':
          description: 서버 오류

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # 선생님 계정 생성 요청
    ClassRoomCreateRequest:
      type: object
      properties:
        studentId:
          type: integer
          format: int64
          description: 학생 id
      required:
        - studentId
    ClassRoomCreateResponse:
      type: object
      properties:
        classRoomId:
          type: integer
          format: int64
          description: 방 id
      required:
        - classRoomId
    ClassRoomResponse:
      type: object
      properties:
        classRoomId:
          type: integer
          format: int64
          description: 방 id
        studentId:
          type: integer
          format: int64
          description: 학생 id
        status:
          type: string
          description: 방 상태
      required:
        - classRoomId
        - studentId
        - status
    ClassRoomEnterResponse:
      type: object
      properties:
        token:
          type: string
          description: livekit token
      required:
        - token
