openapi: 3.0.0
info:
  title: 학생 API
  version: 1.0.0
  description: 학생 관련 API

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /students:
    post:
      summary: 학생 계정 생성
      security:
        - BearerAuth: [ ]
      operationId: createStudent
      tags:
        - Student
      requestBody:
        description: 학생 계정 생성 요청
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentCreateRequest'
      responses:
        '200':
          description: 성공
        '400':
          description: 잘못된 요청

  /students/my:
    get:
      summary: 내 정보 조회
      description: 내 정보를 조회합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentResponse'
        '400':
          description: 잘못된 요청입니다.

    patch:
      summary: 내 정보 수정
      description: 내 정보를 수정합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      requestBody:
        description: 수정할 정보
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentUpdateRequest'
      responses:
        '200':
          description: 성공
        '400':
          description: 잘못된 요청입니다.

  /students/{id}/next-class:
    get:
      summary: 다음 수업 조회
      description: 다음 수업을 조회합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 학생 ID
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseResponse'
        '400':
          description: 잘못된 요청입니다.

  /students/{id}/courses:
    get:
      summary: 수강 중인 강좌 조회
      description: 수강 중인 강좌를 조회합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 학생 ID
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseResponse'
        '400':
          description: 잘못된 요청입니다.

  /students/{id}/favorites:
    get:
      summary: 선생님 즐겨찾기 목록 조회
      description: 즐겨찾기한 선생님을 조회합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 학생 ID
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeacherResponse'
        '400':
          description: 잘못된 요청입니다.

    post:
      summary: 선생님 즐겨찾기 추가
      description: 선생님을 즐겨찾기에 추가합니다.
      tags:
        - Student
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 학생 ID
      requestBody:
        description: 즐겨찾기할 선생님 ID
        required: true
        content:
          application/json:
            schema:
              type: integer
      responses:
        '200':
          description: 성공
        '400':
          description: 잘못된 요청입니다.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    StudentCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: 학생 이름
      required:
        - name

    StudentResponse:
      type: object
      properties:
        id:
          type: integer
          description: 학생 ID
        name:
          type: string
          description: 학생 이름
      required:
        - id
        - name

    StudentUpdateRequest:
      type: object
      properties:
        name:
          type: string
          description: 바꿀 이름
      required:
        - name

    CourseResponse:
      type: object
      properties:
        id:
          type: integer
          description: 수업 ID
        name:
          type: string
          description: 수업 이름
      required:
        - id
        - name

    TeacherResponse:
      type: object
      properties:
        id:
          type: integer
          description: 선생님 ID
        name:
          type: string
          description: 선생님 이름
        experience:
          type: integer
          description: 선생님 경력
        profileImage:
          type: string
          description: 선생님 프로필 이미지 URL
        summary:
          type: string
          description: 선생님 한줄 소개
        favorite:
          type: boolean
          description: 즐겨찾기 여부
        verified:
          type: boolean
          description: 선생님 인증 여부
        rating:
          type: number
          description: 선생님 평점
        reviewCount:
          type: integer
          description: 선생님 리뷰 수
