spring:
  profiles:
    group:
      local:
        - app
        - domain
      dev:
        - app-dev
        - domain-dev
    active: local

  config:
    import: classpath:application-dev.yml

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---

spring:
  config:
    activate:
      on-profile: local

jasypt:
  encryptor:
    password: hello

aws:
  cloudfront-url: https://sadniasdksmkadmiqiq.com
