spring:
  profiles:
    active: local
    include:
      - app
      - domain

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---

spring:
  config:
    activate:
      on-profile: local

aws:
  cloudfront-url: https://sadniasdksmkadmiqiq.com

logging:
  discord:
    webhook-url:
