spring:
  config:
    activate:
      on-profile: dev

jwt:
  access-token:
    secret: ENC(xF6NiqtnrjWv5c92AtD5KEMgozzVkfAobomlV5kUhMscsOvXOLd7NDB5XbBCV0u+fuuhZPnOsMehe5cgf1CU3VqyyuOsM03JdfRLItnXSJo=)
    expire-second: 1800
  refresh-token:
    secret: ENC(8Lb9/yU6rTEG5TEQyWM/I4tr3U1fDZlTKu1Nrz0DCUV24WCN3BqpQ5NfKKrj72yuRtHAJdfjP0zIhrqXwSpJt754fRmlqc6c9puvdgQrmhY=)
    expire-second: 1296000

s3:
  bucket: ENC(GDUOuAxgh483HzqPJNNl4huu/O6rav7+)

livekit:
  secret:
    key: ENC(ieLT6uq3nLSVVnQpagsplaU+9iIK2VMLZd71vvdvJQyHQcyWioa1ZgIu12B/i2SEbE8Y2wOF1U2DfHUBk2hvCHFGIw1iChS2edp3HdmAa/g=)
    expire-second: 1800
  api-key: ENC(WVj0/w+gEONcy2keSS6nvT4s2+2IQAMZn0TwadpuGZHQJAVNyu+baVjLy28u0vL15hrzm6jFcMlKTUP/UxWO9A==)
