jwt:
  access-token:
    secret: akdsmksamdkdamkdkmasdkmdakmsdnmbambmb4294g4kokgo4k4g
    expire-second: 1800
  refresh-token:
    secret: fkimf224mg42mg24mk4gmvnsnbnaoaofkl23lf3f329m2ollfflf4f4
    expire-second: 1296000

