spring:
  config:
    activate:
      on-profile: local

jwt:
  access-token:
    secret: xl32frB+bFvlJ4/lgWRSmCqufDua1fEFuX+XAI7Nki57y8a63RGfCFEfjGwG+ZR352FypLWyoLSVF58JwFQuAg==
    expire-second: 1800
  refresh-token:
    secret: 9FhG6PRid62YTNTg25J75aT++rFnrfSzyuPs+3+sEK6f57AoJrKj6h2G+v4H/njghWg14b26xa71P3nEiVZDqw==
    expire-second: 1296000

livekit:
  secret:
    key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
    expire-second: 1800
  api-key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest

s3:
  bucket: bucketname
