plugins {
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation project(':domain')
    testImplementation 'org.jetbrains.kotlin:kotlin-test'

    // jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    // livekit
    implementation 'io.livekit:livekit-server:0.8.5'
}

bootJar {
    enabled = false
}
